version: "3"
services:
    cars:
        image: leandrocosta1614/docker-car-service
        container_name: cars
        ports:
          - "8666:8666"
    pedestres:
        image: leandrocosta1614/docker-pedestre-service
        container_name: pedestres
        ports:
          - "8080:8080"
    spws:
        image: leandrocosta1614/docker-spws
        container_name: spws
        ports:
          - "8042:8042"
    gateway:
        image: leandrocosta1614/docker-api-gateway
        container_name: gateway
        ports:
          - "8888:8888"
    website:
        image: leandrocosta1614/docker-website
        container_name: website
        ports:
          - "8333:8333"
